### ISSUE TITLE
resulting appcmd command in the iis_vdir :add action no longer appends trailing '/' to app.name

### ISSUE THREAD

**Issue by brianjsykes** [chef-cookbooks/iis#361] opened 2017-05-15 22:53 UTC
### Cookbook version
6.5.1

### Chef-client version
12.12.15

### Platform Details
Windows 2008r2

### Scenario:
creating vdirs

### Steps to Reproduce:
```
       iis_vdir "Creating vDir /foo for Sitename" do
            name 'Sitename'
            path '/foo'
            physical_path 'path\to\foo
            action :add
          end 
```

### Expected Result:
`appcmd.exe add vdir /app.name:"Sitename/" /path:"/foo" /physicalPath:"path\to\foo" /logonMethod:ClearText /allowSubDirConfig:true /commit:\"MACHINE/WEBROOT/APPHOST\"`

### Actual Result:
`appcmd.exe add vdir /app.name:"Sitename" /path:"/foo" /physicalPath:"path\to\foo" /logonMethod:ClearText /allowSubDirConfig:true /commit:\"MACHINE/WEBROOT/APPHOST\"`

**Comment by EasyAsABC123** [comment] 2017-05-16 02:27
Working as intended, not a bug.  https://github.com/chef-cookbooks/iis#iis_vdir

Not a bad feature request, but not a bug

**Comment by EasyAsABC123** [comment] 2017-05-16 03:53
Resolved by #363 in release [v6.5.2](https://github.com/chef-cookbooks/iis/pull/364)

**Closed by EasyAsABC123** 2017-05-16 03:53 UTC
Labels: Type: Feature Request

**Comment by brianjsykes** [comment] 2017-05-16 04:26
I want to be sure that I'm getting this right since I work in a large organization with several high traffic applications...

- In our cookbook that uses the iis_vdir resource, we've been passing the 'name' property (or 'application_name' previously) to the resource as, simply, 'AppName'
- When I look back at previous logs, I see that the appcmd command ended up using 'AppName/' as the .name parameter
- When we updated our wrapper cookbook to account for the switch from 'application_name' to 'name', we still found that our deployments were breaking when the iis_vdir ':add' action would run. 
The error we have been seeing is **ERROR ( message:Cannot find APP object with identifier "AppName". )**
- So, I tried adding a trailing slash to the 'name' param, and things seemed to work as normal.

I'm totally fine with appending the slash, but I want to be sure that by adding it I may not be causing another issue downstream (we have way too many applications for me to understand all of the ways this resource is being used). 

Am I correct that there was a breaking change here, or is there another factor I am getting wrong? I'm not deeply familiar with appcmd commands, so want to be sure I'm not potentially causing more issues...

**Comment by EasyAsABC123** [comment] 2017-05-16 05:25
V6.5.2 allows for the way you were doing it or the way you changed to. But to answer the question, correct that is the fix simply add a / to the end of update to 6.5.2 which I release about and hour ago.  It is on supermarket

**Comment by brianjsykes** [comment] 2017-05-16 16:16
Awesome. Thanks, Justin!

**Comment by EasyAsABC123** [comment] 2017-05-16 16:22
@brianjsykes np, glad i could help.

**Comment by fabioce** [comment] 2019-10-12 16:29
Hello I have the opposite problem.
STDOUT: ERROR ( message:Cannot find APP object with identifier "AppName/". )

**Comment by EasyAsABC123** [comment] 2019-10-12 16:44
‘’’
iis_vdir 'Default Web Site/' do
  action :add
  path '/Content/Test'
  physical_path 'C:\wwwroot\shared\test'
end
‘’’

It’s an example of how it works

**Comment by fabioce** [comment] 2019-10-12 18:46
Yes I know, but if I write my recipe:
iis_vdir "nothing important" do
          action :add
          name "site_name/"
          path "/mypath"
          physical_path "\\\\fileserver\\folder"
        end

or:

iis_vdir "nothing important" do
          action :add
          name "site_name"
          path "/mypath"
          physical_path "\\\\fileserver\\folder"
        end

The error is the same.

STDOUT: ERROR ( message:Cannot find APP object with identifier "AppName/". )

I think I need to specify the sitename without /

**Comment by EasyAsABC123** [comment] 2019-10-13 01:34
Correct it concatenates the site name to the name I think

**Comment by fabioce** [comment] 2019-10-13 06:40
Yes understand, but I cannot be able to solve my error.
STDOUT: ERROR ( message:Cannot find APP object with identifier "AppName/". )
