### ISSUE TITLE
Error 50: Adding ISAPIFilter on server 2016

### ISSUE THREAD

**Issue by mitchflores** [chef-cookbooks/iis#365] opened 2017-05-16 13:08 UTC
### Cookbook version
6.5.1

### Chef-client version
12.20.3

### Platform Details
Windows 2016

### Scenario:
Error executing action 'install' on resource 'windows_feature_dism[IIS-ISAPIFilter]'

### Steps to Reproduce:
`include_recipe "iis::mod_aspnet45"`

### Expected Result:
Should be successful

### Actual Result:
I get Error 50 DISM.

**Comment by EasyAsABC123** [comment] 2017-05-16 14:48
I wonder if this is related to #334

**Comment by mitchflores** [comment] 2017-05-17 03:43
Hi @EasyAsABC123 , I guess it's not. I'm running it on Windows 10 / server 2016. I think it's not evaluating correctly on this part:
`mod_isapi.rb` at line 23

```ruby
features = if Opscode::IIS::Helper.older_than_windows2008r2?
             %w(Web-ISAPI-Filter Web-ISAPI-Ext)
           else
             %w(IIS-ISAPIFilter IIS-ISAPIExtensions)
           end
```

It should pick `Web-ISAPI-Filter Web-ISAPI-Ext` but the current scenario it gets `IIS-ISAPIFilter IIS-ISAPIExtensions`

**Comment by EasyAsABC123** [comment] 2017-05-17 13:13
Cool i'll look at it, but windows server 2016 isn't fully tested

**Comment by EasyAsABC123** [comment] 2017-11-15 14:47
duplicate of #387

**Closed by EasyAsABC123** 2017-11-15 14:47 UTC
Labels: Type: Maintenance
